[tool.mypy]
disallow_untyped_defs = true
warn_unused_ignores = true
ignore_missing_imports = false

# refer to: https://docs.pytest.org/en/stable/mark.html
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov-report term-missing --cov-report xml --cov=src/"
testpaths = [
    "tests",
]
markers = [
    "asyncio"
]
pythonpath='./src'